// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// BT_EM
List BT_EM(S4 W, double a, double b, int maxit, double epsilon);
RcppExport SEXP _BradleyTerryScalable_BT_EM(SEXP WSEXP, SEXP aSEXP, SEXP bSEXP, SEXP maxitSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type a(aSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(BT_EM(W, a, b, maxit, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// ILSR
List ILSR(S4 W, int maxit, double epsilon);
RcppExport SEXP _BradleyTerryScalable_ILSR(SEXP WSEXP, SEXP maxitSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< S4 >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(ILSR(W, maxit, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// btprob_vec
arma::sp_mat btprob_vec(arma::vec pi);
RcppExport SEXP _BradleyTerryScalable_btprob_vec(SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    rcpp_result_gen = Rcpp::wrap(btprob_vec(pi));
    return rcpp_result_gen;
END_RCPP
}
// fitted_vec
arma::sp_mat fitted_vec(arma::vec pi, arma::sp_mat N);
RcppExport SEXP _BradleyTerryScalable_fitted_vec(SEXP piSEXP, SEXP NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type pi(piSEXP);
    Rcpp::traits::input_parameter< arma::sp_mat >::type N(NSEXP);
    rcpp_result_gen = Rcpp::wrap(fitted_vec(pi, N));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BradleyTerryScalable_BT_EM", (DL_FUNC) &_BradleyTerryScalable_BT_EM, 5},
    {"_BradleyTerryScalable_ILSR", (DL_FUNC) &_BradleyTerryScalable_ILSR, 3},
    {"_BradleyTerryScalable_btprob_vec", (DL_FUNC) &_BradleyTerryScalable_btprob_vec, 1},
    {"_BradleyTerryScalable_fitted_vec", (DL_FUNC) &_BradleyTerryScalable_fitted_vec, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_BradleyTerryScalable(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
