# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
BT_EM <- function(W, a, b, maxit = 5000L, epsilon = 1e-3) {
    .Call('SBT_BT_EM', PACKAGE = 'SBT', W, a, b, maxit, epsilon)
}

#' @export
btprob_vec_sp <- function(pi) {
    .Call('SBT_btprob_vec_sp', PACKAGE = 'SBT', pi)
}

#' @export
btprob_vec <- function(pi) {
    .Call('SBT_btprob_vec', PACKAGE = 'SBT', pi)
}

#' @export
btfitted_vec_d <- function(pi, N) {
    .Call('SBT_btfitted_vec_d', PACKAGE = 'SBT', pi, N)
}

#' @export
btfitted_vec_sp <- function(pi, N) {
    .Call('SBT_btfitted_vec_sp', PACKAGE = 'SBT', pi, N)
}

#' @export
btfitted_vec_sp_sp <- function(pi, N) {
    .Call('SBT_btfitted_vec_sp_sp', PACKAGE = 'SBT', pi, N)
}

#' @export
ILSR <- function(W, maxit = 5000L, epsilon = 1e-3) {
    .Call('SBT_ILSR', PACKAGE = 'SBT', W, maxit, epsilon)
}

