# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BT_EM_arma <- function(W_R, a, b, maxit = 100L, start = "eig", epsilon = 1e-2) {
    .Call('SBT_BT_EM_arma', PACKAGE = 'SBT', W_R, a, b, maxit, start, epsilon)
}

